# Generated by Django 4.2.9 on 2026-02-09 14:25

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="CSV file containing equipment data",
                        upload_to="datasets/",
                        validators=[api.models.validate_csv_file],
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the dataset was uploaded",
                    ),
                ),
                (
                    "summary_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Computed analytics summary stored as JSON",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the dataset",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset Upload",
                "verbose_name_plural": "Dataset Uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
